version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'assessment'
       MYSQL_ROOT_PASSWORD: 'assessment123'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-drf-swagger
    ports:
      - "8000:8000"
    depends_on:
      - db
